
stages:
  - check
  - test
  - build
  - test_deploy
  - deploy

variables:
  # Versioned esp-idf-doc env image to use for all document building jobs
  ESP_DOCS_ENV_IMAGE: "$CI_DOCKER_REGISTRY/esp-idf-doc-env-v5.0:2-2"
  PYTHON_VER: 3.7.10
  ESP_DOCS_PATH: "$CI_PROJECT_DIR"
  IDF_PATH: $CI_PROJECT_DIR/esp-idf
  IDF_REPO: ${GITLAB_SSH_SERVER}/espressif/esp-idf.git

.before_script_minimal:
  before_script:
    - source ci/setup_python.sh
    - source ci/utils.sh

.before_script_prepare_build:
  before_script:
    # Use CI Tools
    - curl -sSL ${CIT_LOADER_URL} | sh
    - source citools/import_functions
    - source ci/setup_python.sh
    - source ci/utils.sh
    # Purge any old esp-docs versions
    - pip3 uninstall -y esp-docs
    - pip3 install .

check_setup:
  stage: check
  image: $ESP_DOCS_ENV_IMAGE
  extends:
    - .before_script_minimal
  script:
    - pip3 install .

check_python_style:
  stage: check
  image: $ESP_DOCS_ENV_IMAGE
  extends:
    - .before_script_minimal
  script:
    - python -m flake8 --config=$ESP_DOCS_PATH/.flake8 $ESP_DOCS_PATH

test_extensions_ut:
  stage: test
  image: $ESP_DOCS_ENV_IMAGE
  extends:
    - .before_script_prepare_build
  script:
    - cd test/unit_tests
    - python test_docs.py
    - python test_esp_extensions.py

test_builds:
  stage: test
  image: $ESP_DOCS_ENV_IMAGE
  extends:
    - .before_script_prepare_build
  script:
    - cd test/build_tests
    - ./build_all.sh

.build_template:
  stage: build
  image: $ESP_DOCS_ENV_IMAGE
  extends:
    - .before_script_prepare_build
  artifacts:
    when: always
    paths:
      - $DOCS_DIR/_build/*/*/html/*
      - $DOCS_DIR/_build/*/*/*.txt
    expire_in: 4 days

build_example_basic:
  extends:
    - .build_template
  variables:
    DOCS_DIR: $CI_PROJECT_DIR/examples/basic
  script:
    - cd "$DOCS_DIR"
    - ./build_example.sh

build_example_doxygen:
  extends:
    - .build_template
  variables:
    DOCS_DIR: $CI_PROJECT_DIR/examples/doxygen
  script:
    - cd $DOCS_DIR
    - ./build_example.sh

build_idf_docs_html:
  extends:
    - .build_template
  variables:
    DOCS_DIR: $CI_PROJECT_DIR/esp-idf/docs
    IDF_COMMIT_ID: 7d680980894fbcc1532f6934c1e3a2f0f8181d64
  script:
      # add gitlab ssh key
    - cit_add_ssh_key "${GITLAB_KEY_PEM}"
    - git clone "${IDF_REPO}"
    - $ESP_DOCS_PATH/ci/set_repo.sh $IDF_COMMIT_ID $IDF_PATH
    - cd $IDF_PATH && tools/idf_tools.py --non-interactive install
    - $IDF_PATH/tools/idf_tools.py install-python-env
    - eval "$($IDF_PATH/tools/idf_tools.py export)"
    - pip install $ESP_DOCS_PATH
    - cd $DOCS_DIR
    - build-docs --skip-reqs-check -l $DOCLANG -t $DOCTGT
  parallel:
    matrix:
      - DOCLANG: ["en", "zh_CN"]
        DOCTGT: ["esp32", "esp32s2", "esp32s3", "esp32c3"]

build_idf_docs_pdf:
  extends:
    - .build_template
  variables:
    DOCS_DIR: $CI_PROJECT_DIR/esp-idf/docs
    IDF_COMMIT_ID: 7d680980894fbcc1532f6934c1e3a2f0f8181d64
  script:
      # add gitlab ssh key
    - cit_add_ssh_key "${GITLAB_KEY_PEM}"
    - git clone "${IDF_REPO}"
    - $ESP_DOCS_PATH/ci/set_repo.sh $IDF_COMMIT_ID $IDF_PATH
    - cd $IDF_PATH && tools/idf_tools.py --non-interactive install
    - $IDF_PATH/tools/idf_tools.py install-python-env
    - eval "$($IDF_PATH/tools/idf_tools.py export)"
    - pip install $ESP_DOCS_PATH
    - cd $DOCS_DIR
    - build-docs --skip-reqs-check -l $DOCLANG -t $DOCTGT -bs latex
  parallel:
    matrix:
      - DOCLANG: ["en", "zh_CN"]
        DOCTGT: ["esp32", "esp32s2", "esp32s3", "esp32c3"]

build_package:
  stage: build
  image: $ESP_DOCS_ENV_IMAGE
  extends:
   - .before_script_minimal
  tags:
    - build
  dependencies: []
  artifacts:
    when: always
    paths:
      - dist/*
  script:
    - python -m pip install build
    - python -m build

.deploy_docs_template:
  stage: test_deploy
  image: $ESP_DOCS_ENV_IMAGE
  extends:
    - .before_script_prepare_build
  variables:
    DOCS_DEPLOY_PRIVATEKEY: "$DOCS_DEPLOY_KEY"
    DOCS_DEPLOY_SERVER: "$DOCS_SERVER"
    DOCS_DEPLOY_SERVER_USER: "$DOCS_SERVER_USER"
    DOCS_DEPLOY_PATH: "$DOCS_PATH"
    DOCS_DEPLOY_URL_BASE: "https://$CI_DOCKER_REGISTRY/docs/esp-idf"
  script:
    - add_doc_server_ssh_keys $DOCS_DEPLOY_PRIVATEKEY $DOCS_DEPLOY_SERVER $DOCS_DEPLOY_SERVER_USER
    - export GIT_VER=$(git describe --always)
    - deploy-docs

deploy_docs_idf:
   extends:
     - .deploy_docs_template
   variables:
     DOCS_BUILD_DIR: "${CI_PROJECT_DIR}/esp-idf/docs/_build/"
     TYPE: "preview"
     DOCS_DEPLOY_PRIVATEKEY: "$DOCS_DEPLOY_KEY"
     DOCS_DEPLOY_SERVER: "$DOCS_SERVER"
     DOCS_DEPLOY_SERVER_USER: "$DOCS_SERVER_USER"
     DOCS_DEPLOY_PATH: "$DOCS_PATH"
     DOCS_DEPLOY_URL_BASE: "https://$DOCS_PREVIEW_SERVER_URL/docs/esp-idf"
   needs:
     - build_idf_docs_html
     - build_idf_docs_pdf

deploy_docs_esp_docs:
  extends:
    - .deploy_docs_template
  only:
    - master
  variables:
    DOCS_BUILD_DIR: "${CI_PROJECT_DIR}/examples/basic/_build/"
    TYPE: "preview"
    DOCS_DEPLOY_PRIVATEKEY: "$DOCS_PROD_DEPLOY_KEY"
    DOCS_DEPLOY_SERVER: "$DOCS_PROD_SERVER"
    DOCS_DEPLOY_SERVER_USER: "$DOCS_PROD_SERVER_USER"
    DOCS_DEPLOY_PATH: "$DOCS_PROD_PATH"
    DOCS_DEPLOY_URL_BASE: "https://docs.espressif.com/projects/esp-docs"
  needs:
    - build_example_basic

deploy_package:
  stage: deploy
  image: $ESP_DOCS_ENV_IMAGE
  extends:
    - .before_script_minimal
  tags:
    - build
  only:
    - master
  when: on_success
  dependencies:
    - build_package
  script:
   - pip3 install .
   - python $ESP_DOCS_PATH/ci/deploy_package.py
